service: resources-service 

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-2
  environment: 
    RDS_HOST: ${file(../learning_dashboard_backend_config/serverless_env.json):RDS_HOST}
    RDS_USER: ${file(../learning_dashboard_backend_config/serverless_env.json):RDS_USER}
    RDS_PASSWORD: ${file(../learning_dashboard_backend_config/serverless_env.json):RDS_PASSWORD}
    RDS_DATABASE: ${file(../learning_dashboard_backend_config/serverless_env.json):RDS_DATABASE}

functions:
  resources:
    handler: resources.handler
    events:
      - http:
          path: resources
          method: get
          cors: true
      - http:
          path: resources
          method: post
          cors: true
      - http:
          path: resources/{resourceId}
          method: post
          cors: true      