service: resources-service 

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-2
  environment: 
    RDS_HOST: ${opt:RDS_HOST}
    RDS_USER: ${opt:RDS_USER}
    RDS_PASSWORD: ${opt:RDS_PASSWORD}
    RDS_DATABASE: ${opt:RDS_DATABASE}

functions:
  resources:
    handler: resources.handler
    events:
      - http:
          path: resources
          method: get
          cors: true